# -*- coding: utf-8 -*-
"""Copy of Pencil Sketch

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HX_8N8yc6z9qgxEjjBdnyc3PulTex45L

OpenCV library is used in Python for converting an image into a pencil sketch.
"""

import cv2 
from google.colab.patches import cv2_imshow

image = cv2.imread("/horse.jpg") 
cv2_imshow(image) 
cv2.waitKey(0)

"""# New Section"""

gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray_image)
cv2.waitKey(0)

"""reversing the colors on the image by subtractin the original color values from 255 """

inverted_image = 255 - gray_image
cv2_imshow(inverted_image)
cv2.waitKey()

"""blur the image by using the Gaussian Function"""

blurred = cv2.GaussianBlur(inverted_image, (5,5),0) 
cv2_imshow(blurred)
cv2.waitKey()

"""Inverting the blurred image"""

inverted_blurred = 255 - blurred
pencil_sketch = cv2.divide(gray_image, inverted_blurred, scale=245.0)
cv2_imshow(pencil_sketch)
cv2.waitKey(0)

"""Original and sketch"""

cv2_imshow( image)
cv2_imshow(pencil_sketch)
cv2.waitKey(0)